# Generated by Django 2.1.5 on 2019-01-26 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='評論')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間')),
            ],
            options={
                'verbose_name': '課程評論',
                'verbose_name_plural': '課程評論',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手機')),
                ('course_name', models.CharField(max_length=50, verbose_name='課程名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間')),
            ],
            options={
                'verbose_name': '用戶諮詢',
                'verbose_name_plural': '用戶諮詢',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間')),
            ],
            options={
                'verbose_name': '用戶課程',
                'verbose_name_plural': '用戶課程',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='數據id')),
                ('fav_type', models.IntegerField(choices=[(1, '課程'), (2, '課程機構'), (3, '講師')], default=1, verbose_name='收藏類型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間')),
            ],
            options={
                'verbose_name': '用戶收藏',
                'verbose_name_plural': '用戶收藏',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='接受用戶')),
                ('message', models.CharField(max_length=500, verbose_name='消息內容')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已讀')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間')),
            ],
            options={
                'verbose_name': '用戶消息',
                'verbose_name_plural': '用戶消息',
            },
        ),
    ]
